name: Telegram Test
on: [workflow_dispatch]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@v0.1.7
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: "üß™ –¢–ï–°–¢ –ë–û–¢–ê!"
